# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Atelier Socle SAS

coverage:
  status:
    project:
      default:
        threshold: 1%
    patch:
      default:
        target: 90%

ignore:
  - "Sources/RTMPKitCLI/**"
  - "Sources/RTMPKitCommands/**"
  - "Sources/RTMPKit/Transport/NIOTransport.swift"
  - "Sources/RTMPKit/Transport/RTMPChannelHandler.swift"
